name: Build and deploy ASP.NET Core + Vite to Azure Web App - rerestore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 프론트 빌드 (Vite 공개키를 빌드 타임에 주입!)
      - name: Install deps & build client
        working-directory: client
        env:
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
        run: |
          npm ci --legacy-peer-deps
          npm run build

      # 새 빌드물을 API/wwwroot로 반영 (기존 정적파일 제거 후 복사)
      - name: Sync client build into API/wwwroot
        shell: pwsh
        run: |
          if (Test-Path "API/wwwroot") { Remove-Item -Recurse -Force "API/wwwroot/*" }
          New-Item -ItemType Directory -Force -Path "API/wwwroot" | Out-Null
          Copy-Item -Recurse -Force "client/dist/*" "API/wwwroot/"

      # 솔루션 수준이 아닌 API 프로젝트 단위로 Publish (경고 제거)
      - name: Publish API
        run: dotnet publish "API/API.csproj" -c Release -o "${{ github.workspace }}\publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}\publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./publish

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3299A948605E4FA194957D05F93AEAD7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0C095B28D054D4EB3D5430EB34D597F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CA9B0B342374DD890EC48D097A7E6D2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: rerestore
          slot-name: Production
          package: ./publish